const CLIENT_MESSAGES = {
  GENERATE_SUDOKU: 'GENERATE_SUDOKU',
  SOLVE_SUDOKU: 'SOLVE_SUDOKU',
  ERROR: 'ERROR'
}

const WORKER_MESSAGES = {
  SUDOKU_SOLVED: 'SUDOKU_SOLVED',
  SUDOKU_GENERATED: 'SUDOKU_GENERATED',
  ERROR: 'ERROR'
}

const BOARD_SIZE = {
  SMALL: 4,
  MEDIUM: 9,
  LARGE: 16
}

export { WORKER_MESSAGES, CLIENT_MESSAGES, BOARD_SIZE }
