const CLIENT_MESSAGES = {
  GENERATE_SUDOKU: 'GENERATE_SUDOKU',
  SOLVE_SUDOKU: 'SOLVE_SUDOKU',
  ERROR: 'ERROR'
}

const BOARD_SIZE = {
  SMALL: 4,
  MEDIUM: 9,
  LARGE: 16
}

export { CLIENT_MESSAGES, BOARD_SIZE }
